name: Artefato Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar Código do Repositório
        uses: actions/checkout@v4

      - name: Gerar Artefato Zip
        run: zip -r Calculadora.zip .

      - name: Publicar Artefato
        uses: actions/upload-artifact@v4
        with:
          name: codigo-Buildado
          path: Calculadora.zip



  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Baixar Código do Repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Instalar Dependências
        run: pip install -r requirements.txt

      - name: Executar Testes
        run: pytest



      - name: Baixar Artefato
        uses: actions/download-artifact@v4
        with:
          name: codigo-Buildado

      - name: extrair Artefato
        run: unzip Calculadora.zip

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - run: echo "Deploy realizado"